// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDATrg5ophGapaZmTnbgVg0tDAJukEMPlU',
    appId: '1:262730352378:web:11ab1368dd9913d12a2b43',
    messagingSenderId: '262730352378',
    projectId: 'sigre-ceti',
    authDomain: 'sigre-ceti.firebaseapp.com',
    storageBucket: 'sigre-ceti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_oKYcgIUT_ddFGXcPKY7cweDyCw15uB4',
    appId: '1:262730352378:android:47cee5cffce6d5432a2b43',
    messagingSenderId: '262730352378',
    projectId: 'sigre-ceti',
    storageBucket: 'sigre-ceti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVr1Nja6G_5ZLX8PPpc2YnZZQwMUyKgg',
    appId: '1:262730352378:ios:ac0723a5857f024a2a2b43',
    messagingSenderId: '262730352378',
    projectId: 'sigre-ceti',
    storageBucket: 'sigre-ceti.firebasestorage.app',
    iosBundleId: 'com.example.sigreCeti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASVr1Nja6G_5ZLX8PPpc2YnZZQwMUyKgg',
    appId: '1:262730352378:ios:ac0723a5857f024a2a2b43',
    messagingSenderId: '262730352378',
    projectId: 'sigre-ceti',
    storageBucket: 'sigre-ceti.firebasestorage.app',
    iosBundleId: 'com.example.sigreCeti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDATrg5ophGapaZmTnbgVg0tDAJukEMPlU',
    appId: '1:262730352378:web:7c30f86bd8f27e892a2b43',
    messagingSenderId: '262730352378',
    projectId: 'sigre-ceti',
    authDomain: 'sigre-ceti.firebaseapp.com',
    storageBucket: 'sigre-ceti.firebasestorage.app',
  );
}
